name: Marker-position
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - numpy
  - scipy
  - pandas
  - matplotlib
  - ipykernel
  - jupyter
  - ipywidgets
  - ezc3d
  - kineticstoolkit
  - pip:
    - tensorflow
    - keras
